"use client";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthContentProvider } from "@/context/AuthContext";

const poppins = Poppins({
  weight: ["400", "600", "800"],
  subsets: ["latin"],
  display: "swap",
});

// export const metadata = {
//   title: "Next Admin",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} relative min-h-screen bg-light-grey`}
      >
        <AuthContentProvider>{children}</AuthContentProvider>
      </body>
    </html>
  );
}
